version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: meu_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 121314
      POSTGRES_DB: controle_veiculo
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    networks:
      - minha_rede

  springboot:
    build: .
    container_name: minha_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/controle_veiculo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 121314
    depends_on:
      - postgres
    networks:
      - minha_rede

volumes:
  db_data:

networks:
  minha_rede:
    driver: bridge

